modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="hz_spawn_control"
version="${mod_version}"
displayName="HZ Spawn Control"
description="Server-side spawn tables, surfaces and local population limits."
[[dependencies.hz_spawn_control]]
modId="forge"
mandatory=true
versionRange="[47.4.21,)"
ordering="NONE"
side="BOTH"
[[dependencies.hz_spawn_control]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
[[dependencies.hz_spawn_control]]
modId="epichunt"
mandatory=true
versionRange="[1.4.2,)"
ordering="AFTER"
side="BOTH"
[[dependencies.hz_spawn_control]]
modId="vanillabackport"
mandatory=true
versionRange="[1.1.7.10,)"
ordering="AFTER"
side="BOTH"
